### PR TITLE
Add CXXFLAGS to unifyfs-ls

### LINKED ISSUE #738: Compile errors on GCC 4 from PR 736
### Describe the problem you're observing
UnifyFS is now failing to build on the default compiler on LC systems (GCC v4.9.3) since PR #736 was merged.

The issues are stemming from `unifyfs-ls.cpp`.

### Describe how to reproduce the problem

Build UnifyFS using GCC v4.9.3

First failed in GitLab CI, reproduced manually as well.

### Include any warning or errors or releveant debugging data

```
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp: In function ‘int main(int, char**)’:
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:95:10: error: ‘it’ does not name a type
     auto it = file_set.cbegin();
          ^
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:96:12: error: ‘it’ was not declared in this scope
     while (it != file_set.cend()) {
            ^
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:96:27: error: ‘class std::set<unifyfs_server_file_meta, CompareByFilename>’ has no member named ‘cend’
     while (it != file_set.cend()) {
                           ^
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:109:5: error: ‘it’ was not declared in this scope
     it = file_set.cbegin();
     ^
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:109:19: error: ‘class std::set<unifyfs_server_file_meta, CompareByFilename>’ has no member named ‘cbegin’
     it = file_set.cbegin();
                   ^
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:111:26: error: ‘free’ was not declared in this scope
         free(it->filename);
                          ^
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp: In function ‘void parseOpts(int, char**, CommandOptions&)’:
../../../../util/unifyfs-api-client/src/unifyfs-ls.cpp:194:28: error: ‘exit’ was not declared in this scope
                     exit( 0);
                            ^
make[4]: *** [Makefile:639: unifyfs_ls-unifyfs-ls.o] Error 1
```

### PR DESCRIPTION
**Pull request by CamStan**
### Description

Add `-std=c++11` CXXFLAGS to the `unifyfs-ls` target in order to build on GCC v4.9.3.

### Motivation and Context

Fixes #738 

### How Has This Been Tested?

Built successfully locally with GCC v4.9.3

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [ ] ~~I have updated the documentation accordingly.~~
- [x] I have read the **CONTRIBUTING** document.
- [ ] ~~I have added tests to cover my changes.~~
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

### CODE REVIEW

**Comment by CamStan** [comment]
ping @rgmiller. For some reason it won't let me request you as a reviewer.

**Review by MichaelBrim — APPROVED** [review]
